version: '3.1'

services: 
    node_test:
        container_name: node_test
        build: .
        ports: 
            - '3005:3000'
        volumes: 
            - c:/Users/Enes/AppData/Local/Google/Chrome/User Data/Default:/data/json