version: '3.1'

services: 
    node_test:
        container_name: node_test
        build: .
        image: enesusta/bookmarks-server:1
        ports: 
            - '9050:3000'
        volumes: 
            - c:/Users/Enes/AppData/Local/Google/Chrome/User Data/Default:/data/json